# Generated by Django 4.0.5 on 2023-10-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_photo', models.ImageField(upload_to='\\project_photo')),
                ('project_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_photo', models.ImageField(upload_to='\\company_photo')),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
